### ISSUE TITLE
Abolish `PeriodicTimer` and determine the next time when something has to run

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/NCronJob#13]
Currently, a periodic timer checks for next runs.
That is inefficient and opens a surface where jobs run too late (if the Interval is set to a high Timeout).

Instead an approach should be chosen, where the next run-date is calculated.
This should work for instant jobs as well!

**Comment by Kamyab7** [comment]
Hi @linkdotnet, thanks for creating such a nice job scheduler.
I was investigating this a bit around this issue and something crossed my mind that I want to share with you.
Instead of using a background service to use the periodic timer for executing the next job we can define a timer for each job and do something like this.

``` csharp
Timer timer = new Timer(DoSomething, null, TimeSpan.Zero, TimeSpan.FromSeconds(10));

static void DoSomething(object? state)
{
    // This function will be executed when the timer elapses
    Console.WriteLine("Function executed at: " + DateTime.Now);
    // Call your desired function here
}
```

**Comment by linkdotnet** [comment]
> Hi @linkdotnet, thanks for creating such a nice job scheduler. I was investigating this a bit around this issue and something crossed my mind that I want to share with you. Instead of using a background service to use the periodic timer for executing the next job we can define a timer for each job and do something like this.
> 
> ```cs
> Timer timer = new Timer(DoSomething, null, TimeSpan.Zero, TimeSpan.FromSeconds(10));
> 
> static void DoSomething(object? state)
> {
>     // This function will be executed when the timer elapses
>     Console.WriteLine("Function executed at: " + DateTime.Now);
>     // Call your desired function here
> }
> ```

First of all, thanks (again) for jumping in and the kind words. 
I do like the timer idea a lot. It would even abolish the need for an isolation level (if I am not wrong here).

The only thing we might wanna keep in mind is that we might want to introduce maximal degree of parallelism. While I don’t expect that out of the box we need a way of tracking the status.

the periodic timer was convenient because you can always see it as kind of a snapshot to look what is going on.

I am currently on vacation so I can only give you ideas or gather ideas with you, if you are up to it.

to be honest that would be something to make it as a v1. 

In either case - thanks for the kind words and feedback! Very nice idea

**Comment by linkdotnet** [comment]
Just a question @Kamyab7  - do you wanna give it a shot and try?

**Comment by linkdotnet** [comment]
I probably will give your idea a shot

**Comment by linkdotnet** [comment]
Done. @Kamyab7 I settled on `Task.Delay` so, by default, we have `Isolation.NewTask`.
Therefore I could abolish that as well.

**Comment by Kamyab7** [comment]
@linkdotnet Wow you are super fast I wish one day I would be able to write code as well as you do.

**Comment by linkdotnet** [comment]
The rough draft is done - I did some refactoring before to make it easier for myself.
But thank you for the kind words, have to patch out some rough edges, maybe bringing `IsolationLevel` back
