### ISSUE TITLE
Duplicate "Running job" logs?

### ISSUE THREAD

**Issue by ryanbuening** [linkdotnet/NCronJob#19]
Nice library! I'm not sure if this is intended, but I'm seeing duplicate log messages displayed when running a job:

![image](https://github.com/linkdotnet/NCronJob/assets/812974/bf32913e-c49a-48e2-b20f-66258f7dfdea)

One has `Running job:` with colon and one `Running job` without a colon. It is a bit deceiving to see duplicate logs.

**Comment by linkdotnet** [comment]
In Short - No :) so thanks for reporting.
Which version of the library are you running?

**Comment by ryanbuening** [comment]
I believe the latest bits: `2.0.3`

**Comment by ryanbuening** [comment]
Thanks!
