### ISSUE TITLE
Configuration of degree of parallelism

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/NCronJob#4]
The options should allow a value that indicates how many jobs of a given type can run in parallel.

The configuration should be done via the registration of the job itself:
```csharp
Services.AddCronJob<TheJob>(p => p.MaximumConcurrentRuns = 1);
```

If there is a run and `MaximumConcurrentRuns` is reached, the upcoming run will be omitted.
We could introduce another flag that indicates what should happen to the run:
```csharp
public enum MaximumRunStrategy
{
  Omit = 0, // This would be the default - we just "drop" the run
  Reschedule = 1, // We would push the job run to the next possible scheduled run and try again
}
```

So a registration could look like this:
```csharp
Services.AddCronJob<TheJob>(p => 
{
  p.MaximumConcurrentRuns = 1;
  p.MaximumRunStrategy = MaximumRunStrategy.Reschedule;
});
```

## Workaround

There is a current workaround, that a job itself can implement to achieve the same.
Here an example of a job that only allows one running instance at a time:

```csharp
public class MyJob : IJob
{
  private static readonly SemaphoreSlim Semaphore = new(1, 1);

  public async Task RunAsync(JobExecutionContext context, CancellationToken token)
  {
    var hasLock = await Semaphore.WaitAsync(0, token); // Try to grab the handle - if false then there is another job running
    if (hasLock)
    {
      return;
    } 
    try
    {
        // Job logic
    }
    finally
    {
        Semaphore.Release();
    }
  }
}
```

**Comment by falvarez1** [comment]
FYI, some of this is being handled in PR #21

**Comment by linkdotnet** [comment]
In its current version you would have to implement the lock in the job (like redis)

**Comment by falvarez1** [comment]
> My .NET applications run load balanced on multiple servers. If I schedule a job to run every morning, but I only want it to run once, does NCronJob provide any mechanism to handle this? Or would this involve implementing some kind of external locking mechanism?

@ryanbuening this PR does not handle Mutex locking nor distributed locking. I recommend to take a look at the [DistributedLock](https://github.com/madelson/DistributedLock) library for help with that.

**Comment by ryanbuening** [comment]
> take a look at the DistributedLock library

Very cool. Thanks!
