### ISSUE TITLE
Suggestion: Resolve job instances from service scope

### ISSUE THREAD

**Issue by mookid8000** [linkdotnet/NCronJob#5]
Hi there, it's an excellent idea to build a cron expression-enabled job scheduler for .NET 👍 I especially like how it aligns with modern, idiomatic .NET, and it looks like it's very low on ceremony. Many ⭐ in my book for that!

One, tiny thing I suggest get changed though, is the thing about jobs being singletons. From my point of view, there's absolutely NO reason why they should not be transient/scoped and then be resolved from a service scope, as each job execution lends itself PERFECTLY to the scoped model.

Maybe you have a good reason for this design decision? Or maybe it's one of those things that just turn out in one way or another because noone had a strong opinion about it, and that's why I'm here to make you aware that a modern .NET developer would absolutely expect a service scope around anything that can conceptually be thought of as a scope (which a job execution can).

Just my 2 cents. 🙂 Oh, and if you need help with this, I would be happy to submit a PR.

**Comment by mdissel** [comment]
Maybe add an option to JobOption, ExecuteAsSingleton = true/false

**Comment by linkdotnet** [comment]
That is a very valid reason - and on second look I am not sure what drove me to that decision to be very honest.
I started this project some months ago, stopped working on it, and picked it up.
My initial reasoning was that jobs should be as stateless as possible - and recurring jobs "benefit" from less allocations and setup if they are singleton.

That said, I am inclined to register them transient by default.
I also like @mdissel proposal to have a flag, indicating whether or not the job is a singleton, which is `false` by default.

**Comment by linkdotnet** [comment]
@mookid8000 There is also the option to create a scope for the job itself - so every job would run as scoped and is registered `AddScoped<TJob>`.
Have to think about the benefits of that approach.

**Comment by linkdotnet** [comment]
I released `v0.9.3` that registers services as transient. I am open for discussion whether or not to implement a scope that is created for the job.

**Comment by mdissel** [comment]
I think people will expect a new scope when the job is executed and properly destroyed.

**Comment by mdissel** [comment]
Just a small comment, when jobs are executed on the same time, they share the same scope, but are run on different threads. I don't think you can assume that the used services are thread-safe (for example IDBConnection related services)

**Comment by mookid8000** [comment]
Yeah I agree with @mdissel that the new implementation is a little bit too in-between.

_Every job execution_ (as in: one job that executes once) should be resolved in its own scope.  This way, the job can e.g. have a scoped Entity Framework data context and trust it to be shared throughout one single execution, committing changes at the end. 

This would align with how e.g. ASP.NET Core executes each web request in its own scope and basically any other thing in .NET that  has something that can be thought of as a "request" (e.g. my own [Rebus](https://github.com/rebus-org/Rebus) via [Rebus.ServiceProvider](https://github.com/rebus-org/Rebus.ServiceProvider) will treat the handling of each incoming message as a scope).

**Comment by linkdotnet** [comment]
Fair enoigh - I do a release now, that fixes that.
