### ISSUE TITLE
Trigger jobs that respects concurrency config

### ISSUE THREAD

**Issue by KorsG** [linkdotnet/NCronJob#52]
**Is your feature request related to a problem? Please describe.**
I was playing around with the library as a light-weight alternative to Hangfire, but we often need to trigger scheduled jobs manually via UI/API which should respect the concurrency configuration of the jobs being triggered, but as far as I can tell it is not possible since instant jobs does not check concurrency config. 

**Describe the solution you'd like**
A way to trigger jobs that respects the concurrency config of the job. I actually thought the instants jobs would respect the concurrency config as it is, but I can also see the need to trigger a job that runs regardless. Maybe change the "RunScheduledJob" methods on the IInstantJobRegistry to respects the concurrency config by default and then RunInstantJob should just execute immediately as it is now, because the name implies it. 
Otherwise via another API that signals intent more clearly and does not cause breaking changes - e.g. `IJobRegistry.TriggerScheduledJob(...)` 😊

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by linkdotnet** [comment]
That is a good point and yes indeed currently it "by-passes" the whole approach.
We are aware of that shortcoming and we will address it.

Thanks for the report @KorsG

**Comment by KorsG** [comment]
Sounds good and thanks for looking into it 😊

**Comment by linkdotnet** [comment]
Hey @KorsG - if you use any version higher than `2.4.1-preview`, then the issue should be resolved.
