### ISSUE TITLE
make the timer interval configurable

### ISSUE THREAD

**Issue by mdissel** [linkdotnet/NCronJob#7]
In my sitation it's enough to check for jobs to be started every X minutes instead of every seconds.

https://github.com/linkdotnet/NCronJob/blob/main/src/LinkDotNet.NCronJob/Scheduler/CronScheduler.cs#L27C54-L27C72

**Comment by linkdotnet** [comment]
That's a good point - Currently it is set to one second for instant triggers.

One question to you: If you would have a corn job that is scheduled to run every 5 minutes and you set the timer to 5 minutes, what would be the expectation if you the scheduler runs at 9:32?

Would it execute your job at 9:37 then, right?

**Comment by linkdotnet** [comment]
Will come with the next release

**Comment by linkdotnet** [comment]
You can achieve it via:
```csharp
builder.Services.AddNCronJob(p => p.TimerInterval = TimeSpan.FromSeconds(1));
```

**Comment by mdissel** [comment]
I've seen other schedulers that calculate the wait time for the next job and use that as an interval

**Comment by linkdotnet** [comment]
Will have a look into this - thx
